version: "3"

services:

  #######################################
  # Postgres: The database used by Kong
  #######################################
  kong-database:
    image: postgres:9.6
    restart: on-failure 
    ports:
      - "5432:5432"
    networks:
      - kongha-net
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
    volumes:
     - kong-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 5s
      timeout: 5s
      retries: 5


  #######################################
  # Kong database migration
  #######################################
  kong-migration:
    image: kong:1.3.0
    command: "kong migrations bootstrap"
    networks:
      - kongha-net
    restart: on-failure
    environment:
      KONG_PG_HOST: kong-database
    links:
      - kong-database
    depends_on:
      - kong-database


  #######################################
  # Kong: The API Gateway - NODE 1
  #######################################
  kong:
    image: kong:1.3.0
    restart: on-failure 
    networks:
      - kongha-net
    environment:
      # link to kong-database service
      KONG_PG_HOST: kong-database 
      # or cassandra
      KONG_DATABASE: postgres 
      # port for kong (http)
      KONG_PROXY_LISTEN: 0.0.0.0:8100
      # port for kong (https)
      KONG_PROXY_LISTEN_SSL: 0.0.0.0:8543
      # port for admin
      KONG_ADMIN_LISTEN: 0.0.0.0:8101
    depends_on:
      - kong-migration
      - kong-database
    healthcheck:
      test: ["CMD", "curl", "-f", "http://kong:8101"]
      interval: 5s
      timeout: 2s
      retries: 15
    ports:
      - "8101:8101"
      - "8100:8100"

  #######################################
  # Kong: The API Gateway - NODE 2
  #######################################
  kong2:
    image: kong:1.3.0
    restart: on-failure 
    networks:
      - kongha-net
    environment:
      # link to kong-database service
      KONG_PG_HOST: kong-database 
      # or cassandra
      KONG_DATABASE: postgres 
      # port for kong (http)
      KONG_PROXY_LISTEN: 0.0.0.0:8200
      # port for kong (https)
      KONG_PROXY_LISTEN_SSL: 0.0.0.0:8643
      # port for admin
      KONG_ADMIN_LISTEN: 0.0.0.0:8201
    depends_on:
      - kong-migration
      - kong-database
    healthcheck:
      test: ["CMD", "curl", "-f", "http://kong2:8201"]
      interval: 5s
      timeout: 2s
      retries: 15
    ports:
      - "8201:8201"
      - "8200:8200"


  #######################################
  # Konga database prepare
  #######################################
  konga-prepare:
    image: pantsel/konga:next
    command: "-c prepare -a postgres -u postgresql://kong@kong-database:5432/konga_db"
    networks:
      - kongha-net
    restart: on-failure
    links:
      - kong-database
    depends_on:
      - kong-database

  #######################################
  # Konga: Kong GUI
  #######################################
  konga:
    image: pantsel/konga:next
    restart: on-failure 
    networks:
      - kongha-net
    environment:
      # or cassandra
      DB_ADAPTER: postgres
      # link to kong-database service
      DB_HOST: kong-database 
      DB_USER: kong
      TOKEN_SECRET: km1GUr4RkcQD7DewhJPNXrCuZwcKmqjb
      # konga's db name 
      DB_DATABASE: konga_db 
      NODE_ENV: production
    depends_on:
      - konga-prepare
    links:
      - kong
      - kong2
    ports:
      - "1337:1337"

networks:
  kongha-net:
    driver: bridge

volumes:
  kong-pgdata: