global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
 - job_name: "prometheus"
   static_configs:
     - targets: ["localhost:9090"]

 - job_name: "kong"
   scrape_interval: 5s
   static_configs:
     - targets: ['kong:8001']
       labels:
         alias: "kong"